In [1]:
import cv2
import numpy as np

Gx=[[1,2,1],[0,0,0],[-1,-2,-1]]
Gy=[[1,0,-1],[2,0,-2],[1,0,-1]]
img = cv2.imread("./bird.jpeg")
image = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY )

maskx = np.array(([1,2,1],[0,0,0],[-1,-2,-1]))
masky = np.array(([[1,0,-1],[2,0,-2],[1,0,-1]]))

outputx = cv2.filter2D(image, -1, maskx)
outputy = cv2.filter2D(image, -1, masky)

cv2.imshow("image", outputx)
cv2.waitKey(0)

cv2.imshow("image", outputy)
cv2.waitKey(0)

print(outputx)
print()
print(outputy)

[[ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]
 ...
 [24 22 18 ...  0  0  0]
 [22 20 16 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]]

[[ 0  0  0 ...  0  2  0]
 [ 0  0  0 ...  1  1  0]
 [ 0  0  0 ...  4  1  0]
 ...
 [ 0  0  0 ... 20  4  0]
 [ 0  0  0 ... 24  4  0]
 [ 0  0  0 ... 26  4  0]]
